name: CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run production build
        run: npm run build

 ## deployment on Azure VM using SSH action, those are only for learning purposes
 
  # deploy:
  #   needs: ci
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Deploy to Azure VM
  #       uses: appleboy/ssh-action@v1.2.0
  #       with:
  #         host: ${{ secrets.VM_HOST }}
  #         username: ${{ secrets.VM_USER }}
  #         key: ${{ secrets.VM_SSH_KEY }}
  #         script: |
  #             export NVM_DIR="$HOME/.nvm"
  #             [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

  #             cd ~/pyqverse

  #             git pull origin main
  #             npm ci
  #             npm run build

  #             pm2 restart pyqverse